# -*- coding: utf-8 -*-
"""Build the published gallery of real reports.

WHY A GALLERY AND NOT A LIVE SERVICE. A hosted service for this tool would need
a server that fetches arbitrary URLs on demand, which is a different thing to
run and to defend than the tool itself. What a reader actually wants to know is
what it SAYS about pages they recognise. So the gallery is the real output of
the real tool on real pages, generated by this script, rendered as static
files, and dated.

    python docs/build_gallery.py

It runs the deterministic path only, no key and no model, so anyone can rerun
it and get the same pages back. **It exits non zero if any page fails**, rather
than quietly publishing a gallery with a hole in it. A gallery that silently
drops the page that did not work is exactly the kind of claim this tool exists
to catch.
"""
from __future__ import annotations
import datetime
import html as _html
import io
import os
import sys
import traceback

ICI = os.path.dirname(os.path.abspath(__file__))
RACINE = os.path.dirname(ICI)
sys.path.insert(0, RACINE)

from asterisk import fetch, html as htmlout               # noqa: E402
from asterisk.audit import audit                          # noqa: E402
from asterisk.segment import segment                      # noqa: E402

PAGES = [
    ("spotify-premium", "https://www.spotify.com/us/premium/",
     "A music subscription, on the page that sells the free trial."),
    # Revolut sat here until 2026-08-30, when its server started answering 403
    # to a plain fetch. Left as a comment rather than deleted, because a page
    # that refuses to be read is a fact about the page and not a bug here.
    ("wise-pricing", "https://www.wise.com/gb/pricing/",
     "A money transfer service, on the page about its fees."),
    # EXPECTED TO BE REFUSED, and it is in the gallery for that reason. This
    # page is drawn in the browser and a plain fetch sees a shell. Reporting
    # `nothing found` on it would be the worst thing this tool could do,
    # because silence and a clean bill of health look identical to a reader.
    ("audible-membership", "https://www.audible.com/ep/memberships",
     "A subscription sold on a free trial, drawn in the browser.", "refused"),
    ("shopify-pricing", "https://www.shopify.com/pricing",
     "A commerce platform's price table."),
    ("dropbox-plans", "https://www.dropbox.com/plans",
     "Storage plans, where the word unlimited usually lives."),
    ("agents-for-humans", "https://agentsforhumans.devpost.com/",
     "A hackathon with forty thousand dollars in cash."),
    ("webmcp-challenge", "https://webmcp.devpost.com/",
     "A challenge announcing thirty five thousand dollars."),
    ("xtech-blaise", "https://www.herox.com/xTechIdeaCompetition",
     "An idea competition with a second phase."),
]

GABARIT = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Asterisk, reports on real pages</title>
<style>
 :root{color-scheme:light dark}
 body{max-width:52rem;margin:3rem auto;padding:0 1.2rem;
      font:16px/1.65 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
 h1{font-size:1.7rem;margin-bottom:.2rem}
 .sub{opacity:.75;margin-top:0}
 .card{border:1px solid rgba(128,128,128,.35);border-radius:10px;
       padding:1rem 1.1rem;margin:.9rem 0}
 .card a{font-weight:600;text-decoration:none;font-size:1.05rem}
 .card p{margin:.35rem 0 .2rem}
 .src{font-size:.85rem;opacity:.7;word-break:break-all}
 .n{font-variant-numeric:tabular-nums;font-size:.85rem;opacity:.8}
 footer{margin-top:2.5rem;font-size:.9rem;opacity:.75}
 code{background:rgba(128,128,128,.15);padding:.1rem .3rem;border-radius:4px}
</style></head><body>
<h1>Asterisk, on pages you already know</h1>
<p class="sub">Where an offer page takes back its own headline, and what it
quietly requires of you. Every line below is copied from the page it names.</p>
%(cartes)s
<footer>
<p>Generated on %(date)s by <code>docs/build_gallery.py</code>, deterministic
rules only, no model and no key, so it reruns to the same result. These are
static reports and not a live service, and each one is a snapshot of a page
that can change the day after.</p>
<p>Source and licence, <a href="https://github.com/thibaudlepan77-svg/asterisk">github.com/thibaudlepan77-svg/asterisk</a>, MIT.</p>
</footer></body></html>
"""

CARTE = """<div class="card">
  <a href="gallery/%(nom)s.html">%(titre)s</a>
  <p>%(note)s</p>
  <p class="n">%(compte)d finding%(s)s</p>
  <p class="src">%(url)s</p>
</div>"""


CARTE_REFUS = """<div class="card">
  <p><strong>%(titre)s</strong></p>
  <p>%(note)s</p>
  <p class="n">refused, not audited. %(motif)s</p>
  <p class="src">%(url)s</p>
</div>"""


def main() -> int:
    cartes, rates = [], []
    for entree in PAGES:
        nom, url, note = entree[0], entree[1], entree[2]
        attendu = entree[3] if len(entree) > 3 else "audited"
        try:
            page = fetch.get(url, use_cache=False)
            doc = segment(url=url, html=page) if False else segment(page, url)
            aveugle = doc.looks_unreadable()
            claims, findings = audit(doc, offline=True)
            # THE EXPECTATION IS CHECKED IN BOTH DIRECTIONS. A page listed as
            # refused that suddenly reads fine is as much a change worth
            # knowing as a page that stops reading. A witness that can only
            # fail one way is half a witness.
            if aveugle and attendu != "refused":
                raise RuntimeError("page returned almost no text, it is drawn in the browser")
            if aveugle and attendu == "refused":
                cartes.append(CARTE_REFUS % {
                    "titre": _html.escape(note.split(",")[0]),
                    "note": _html.escape(note), "url": _html.escape(url),
                    "motif": "The page returned almost no text, so the tool says it "
                             "could not be read instead of calling it clean."})
                print("  %-22s refused, as expected" % nom)
                continue
            if not aveugle and attendu == "refused":
                raise RuntimeError("this page was expected to be unreadable and it read "
                                   "fine. Check the list before publishing.")
            sortie = os.path.join(ICI, "gallery", "%s.html" % nom)
            with io.open(sortie, "w", encoding="utf-8") as f:
                f.write(htmlout.render(url, claims, findings, unreadable=aveugle))
            cartes.append(CARTE % {
                "nom": nom, "titre": _html.escape(note.split(",")[0]),
                "note": _html.escape(note), "url": _html.escape(url),
                "compte": len(findings), "s": "" if len(findings) == 1 else "s"})
            print("  %-22s %2d finding(s)" % (nom, len(findings)))
        except Exception as e:
            rates.append((nom, url, "%s" % e))
            print("  %-22s FAILED, %s" % (nom, e))
            if os.environ.get("GALLERY_TRACE"):
                traceback.print_exc()

    if rates:
        print("\n%d page(s) could not be read. The gallery is NOT written." % len(rates))
        print("A gallery that quietly drops the page that failed is the exact claim")
        print("this tool exists to catch. Fix the page list or the fetch, then rerun.")
        return 2

    with io.open(os.path.join(ICI, "index.html"), "w", encoding="utf-8") as f:
        f.write(GABARIT % {"cartes": "\n".join(cartes),
                           "date": datetime.date.today().isoformat()})
    print("\nindex written, %d report(s)." % len(cartes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
